package exceptions

fun erroneousCode() {
    // Uncomment this line to get an exception:
    // val i = "1$".toInt()
}

fun main() {
    erroneousCode()
}